config/routes.rb
Rails.application.routes.draw do
  resources :mappings
  resources :fields
  resources :synchronizations do
    member do
      put 'map'
      get 'map'
      get 'save_localizable'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/synchronization.rb
class Synchronization < ApplicationRecord
  
  has_many :fields, dependent: :destroy
  has_many :mappings, dependent: :destroy
  
  validates_presence_of :name, :source_platform, :target_platform
  
  before_save :save_android_fields, :save_ios_fields
  after_save :save_mapping
  
  def save_android_fields
   document = (source_platform == 'Android' ? source_document : target_document)
   unless document.blank?
      xml_doc = Nokogiri::XML document
      xml_doc.xpath("//string").each_with_index do |string, index|
        field = Field.find_or_initialize_by(name: string[:name], platform: 'Android', synchronization_id: self.id)
        field.is_comment = string.content.starts_with?('<!--')
        field.line = index
        field.field_value = string.content
        field.save
      end
    end
  end
  
  def save_ios_fields
    document = (source_platform == 'iOS' ? source_document : target_document)
    unless document.blank?
      line_count = 0
      is_comment = false
      document.each_line do |line|
        if line.include?('" = "')
          key_value = split_line(line, '" = "')
        elsif line.include?('"="')
          key_value = split_line(line, '"="')
        elsif line.include?('"  = "')
          key_value = split_line(line, '"  = "')
        elsif line.include?('" =  "')
          key_value = split_line(line, '" =  "')
        elsif line.include?('"  =  "')
          key_value = split_line(line, '"  =  "')
        else
          key_value = '""="";'
          is_comment = true # An empty line is treated as a comment line          
        end
      key = get_clean_key(key_value)
      value = get_clean_value(key_value)
      field = Field.find_or_initialize_by(line: line_count, name: key, platform: 'iOS', synchronization_id: self.id)
      field.is_comment = line.starts_with?('/*', '*/', '//') || is_comment
      field.field_value = value
      field.line = line_count
      field.save if field.changed?
      line_count += 1
      end
    end
  end
  
  def save_mapping
    source_fields.each do |source|
      mapping = Mapping.find_or_initialize_by(source_field_id: source.id, synchronization_id: self.id)
      mapping.common_value = source.field_value
      mapping.save validate: false if mapping.changed?
    end
  end
  
  def source_fields
    self.fields.where(:platform => self.source_platform)
  end
  
  def target_fields
    self.fields.where(:platform => self.target_platform)
  end
  
  private
  
  def split_line(line,pattern)
    line.split(pattern)
  end
  
  def get_clean_key(key_value)
    key = key_value[0].delete_prefix('"') if key_value[0]
  end  
  
  def get_clean_value(key_value)
    value = key_value[1].chomp('"').chomp('').delete_suffix('";') if key_value[1]
  end  
  
end

app/controllers/synchronizations_controller.rb
class SynchronizationsController < ApplicationController
  before_action :set_synchronization, only: [:show, :edit, :update, :destroy, :map, :save_localizable]

  # GET /synchronizations
  # GET /synchronizations.json
  def index
    @synchronizations = Synchronization.all
  end
  
  def map
    unless params[:index].blank?
      params[:index].each do |index|
        index = index.to_i
        mapping = Mapping.find_by(
          :source_field_id => params[:source_field_ids][index],
          :synchronization_id => @synchronization
          )      
        if params[:target_field_ids][index].blank?
          mapping.target_field_id = nil
        else  
          mapping.target_field_id = params[:target_field_ids][index]          
        end
        mapping.save
      end     
      
    end  
    respond_to do |format|
      format.html
    end    
  end
  
  def save_localizable
    mappings = Mapping.includes(:source_field).includes(:target_field).where(:synchronization_id => @synchronization).where('target_field_id IS NOT NULL')
    if @synchronization.target_platform == 'iOS'
      @output = ''
      count = 0
      @synchronization.target_document.each_line do |line|                    
        mappings.select{|m| m.target_field.line == count }.each do |mapping|
          if line.include?(mapping.target_field.to_s) && line.blank? == false
            line = "\"#{mapping.target_field.to_s}\" = \"#{mapping.common_value}\""
          end          
        end
        @output += line + "</br>"                
        count += 1
      end            
    end
    respond_to do |format|
        format.html 
    end    
  end

  # GET /synchronizations/1
  # GET /synchronizations/1.json
  def show
  end

  # GET /synchronizations/new
  def new
    @synchronization = Synchronization.new
  end

  # GET /synchronizations/1/edit
  def edit
  end

  # POST /synchronizations
  # POST /synchronizations.json
  def create
    @synchronization = Synchronization.new(synchronization_params)

    respond_to do |format|
      if @synchronization.save
        format.html { redirect_to @synchronization, notice: 'Synchronization was successfully created.' }
        format.json { render :show, status: :created, location: @synchronization }
      else
        format.html { render :new }
        format.json { render json: @synchronization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /synchronizations/1
  # PATCH/PUT /synchronizations/1.json
  def update
    respond_to do |format|
      if @synchronization.update(synchronization_params)
        format.html { redirect_to @synchronization, notice: 'Synchronization was successfully updated.' }
        format.json { render :show, status: :ok, location: @synchronization }
      else
        format.html { render :edit }
        format.json { render json: @synchronization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /synchronizations/1
  # DELETE /synchronizations/1.json
  def destroy
    @synchronization.destroy
    respond_to do |format|
      format.html { redirect_to synchronizations_url, notice: 'Synchronization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_synchronization
      @synchronization = Synchronization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def synchronization_params
      params.require(:synchronization).permit(:name, :source_platform, :source_document, :target_platform, :target_document)
    end
end

app/helpers/synchronizations_helper.rb
module SynchronizationsHelper
end

app/views/synchronizations/_form.html.erb
<%= form_with(model: synchronization, local: true) do |form| %>
  <% if synchronization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(synchronization.errors.count, "error") %> prohibited this synchronization from being saved:</h2>

      <ul>
        <% synchronization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :source_platform %>
    <%= form.select :source_platform, options_for_select(['Android', 'iOS']), class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :source_document %>
    <%= form.text_area :source_document, :cols => 150, :rows => 12, class: 'form-control' %>
  </div>
    
  <div class="field">
    <%= form.label :target_platform %>
    <%= form.select :target_platform, options_for_select(['iOS', 'Android']), class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :target_document %>
    <%= form.text_area :target_document, :cols => 150, :rows => 12, class: 'form-control' %>
  </div>  
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/synchronizations/edit.html.erb
<h1>Editing Synchronization</h1>

<%= render 'form', synchronization: @synchronization %>

<%= link_to 'Show', @synchronization %> |
<%= link_to 'Back', synchronizations_path %>

app/views/synchronizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Synchronizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @synchronizations.each do |synchronization| %>
      <tr>
        <td><%= synchronization.name %></td>
        <td><%= link_to 'Show', synchronization %></td>
        <td><%= link_to 'Edit', edit_synchronization_path(synchronization) %></td>
        <td><%= link_to 'Map', map_synchronization_path(synchronization) %></td>
        <td><%= link_to 'Destroy', synchronization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Synchronization', new_synchronization_path %>

app/views/synchronizations/map.html.erb
<%= form_for :sync_fields, :url => map_synchronization_path, :html => { :method => :put } do |f| %>
    <h1><%= @synchronization.name %></h1>
    <table class="list">
        <tr>
            <th>Source Field</th>
            <th>Target Field</th>
            <th>Value</th>
        </tr>
    <% @synchronization.mappings.each_with_index do |mapping, index| %>    
        <% if field_idx = @synchronization.target_fields.pluck(:id).index(mapping.target_field_id) %>
        <tr>
            <td><%= hidden_field_tag 'index[]', index, :id => nil %>
                <%= hidden_field_tag 'source_field_ids[]', mapping.source_field_id, :id => nil %><%= mapping.source_field.name_with_line %></td>
            <td><%= select_tag 'target_field_ids[]', options_from_collection_for_select(@synchronization.target_fields.order(:name), :id, :name_with_line, 
            :selected => @synchronization.target_fields.slice(field_idx).id), :include_blank => true, :class => 'form-control searchable', :id => nil %></td>
            <td><%= text_field_tag 'common_values[]', mapping.common_value, :class => 'form-control', :id => nil %></td>
        </tr>    
        <% else %>
        <tr>
            <td><%= hidden_field_tag 'index[]', index, :id => nil %>
                <%= hidden_field_tag 'source_field_ids[]', mapping.source_field_id, :id => nil %><%= mapping.source_field.name_with_line %></td>
            <td><%= select_tag 'target_field_ids[]', options_from_collection_for_select(@synchronization.target_fields.order(:name), :id, :name_with_line), :include_blank => true, :class => 'form-control searchable', :id => nil %></td>
            <td><%= text_field_tag 'common_values[]', mapping.common_value, :class => 'form-control', :id => nil %></td>
        </tr>  
        <% end %>    
    <% end %>   
    </table>
    <div class="actions">
        <%= f.submit 'Save' %>
    </div>
<% end %>
<script type="text/javascript">
$(document).ready(function() {
    $('.searchable').select2();
});
</script>

app/views/synchronizations/new.html.erb
<h1>New Synchronization</h1>

<%= render 'form', synchronization: @synchronization %>

<%= link_to 'Back', synchronizations_path %>

app/views/synchronizations/save_localizable.html.erb
<%= raw @output %>

app/views/synchronizations/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @synchronization.name %></h2>

<div class="row">
<div class="col-md-6">
    <h2>Source Fields</h2>
<table style="border: 1px solid black">
    <thead>
        <tr>
            <th>Attribute Name</th>
       </tr>
    </thead>
    <tbody>
<% @synchronization.source_fields.each do |source| %>
<tr><td><%= source.name %></td></tr>
<% end %>
</tbody>
</table>
</div>
<div class="col-md-6">
<h2>Target Template</h2>
<table style="border: 1px solid black">
    <thead>
        <tr>
            <th>Attribute Name</th>
       </tr>
    </thead>
    <tbody>
<% @synchronization.target_fields.each do |target| %>
<tr><td><%= target.name %></td></tr>
<% end %>
</tbody>
</table>
</div>
</div>
<%= link_to 'Edit', edit_synchronization_path(@synchronization) %> |
<%= link_to 'Back', synchronizations_path %>