config/routes.rb
Rails.application.routes.draw do
  resources :mappings
  resources :fields
  resources :synchronizations do
    member do
      put 'map'
      get 'map'
      get 'save_localizable'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mapping.rb
class Mapping < ApplicationRecord
  belongs_to :source_field, class_name: 'Field'
  belongs_to :target_field, class_name: 'Field'
  belongs_to :synchronization
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  before_action :set_mapping, only: [:show, :edit, :update, :destroy]

  # GET /mappings
  # GET /mappings.json
  def index
    @mappings = Mapping.all
  end

  # GET /mappings/1
  # GET /mappings/1.json
  def show
  end

  # GET /mappings/new
  def new
    @mapping = Mapping.new
  end

  # GET /mappings/1/edit
  def edit
  end

  # POST /mappings
  # POST /mappings.json
  def create
    @mapping = Mapping.new(mapping_params)

    respond_to do |format|
      if @mapping.save
        format.html { redirect_to @mapping, notice: 'Mapping was successfully created.' }
        format.json { render :show, status: :created, location: @mapping }
      else
        format.html { render :new }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mappings/1
  # PATCH/PUT /mappings/1.json
  def update
    respond_to do |format|
      if @mapping.update(mapping_params)
        format.html { redirect_to @mapping, notice: 'Mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapping }
      else
        format.html { render :edit }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings/1
  # DELETE /mappings/1.json
  def destroy
    @mapping.destroy
    respond_to do |format|
      format.html { redirect_to mappings_url, notice: 'Mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapping
      @mapping = Mapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mapping_params
      params.require(:mapping).permit(:source_field_id, :target_field_id, :bidirectional, :synchronization_id, :common_value)
    end
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/views/mappings/_form.html.erb
<%= form_with(model: mapping, local: true) do |form| %>
  <% if mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mapping.errors.count, "error") %> prohibited this mapping from being saved:</h2>

      <ul>
        <% mapping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :source_field_id %>
    <%= form.text_field :source_field_id %>
  </div>

  <div class="field">
    <%= form.label :target_field_id %>
    <%= form.text_field :target_field_id %>
  </div>

  <div class="field">
    <%= form.label :bidirectional %>
    <%= form.check_box :bidirectional %>
  </div>

  <div class="field">
    <%= form.label :synchronization_id %>
    <%= form.text_field :synchronization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mappings/edit.html.erb
<h1>Editing Mapping</h1>

<%= render 'form', mapping: @mapping %>

<%= link_to 'Show', @mapping %> |
<%= link_to 'Back', mappings_path %>

app/views/mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Source field</th>
      <th>Target field</th>
      <th>Bidirectional</th>
      <th>Synchronization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mappings.each do |mapping| %>
      <tr>
        <td><%= mapping.source_field_id %></td>
        <td><%= mapping.target_field_id %></td>
        <td><%= mapping.bidirectional %></td>
        <td><%= mapping.synchronization_id %></td>
        <td><%= link_to 'Show', mapping %></td>
        <td><%= link_to 'Edit', edit_mapping_path(mapping) %></td>
        <td><%= link_to 'Destroy', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mapping', new_mapping_path %>

app/views/mappings/new.html.erb
<h1>New Mapping</h1>

<%= render 'form', mapping: @mapping %>

<%= link_to 'Back', mappings_path %>

app/views/mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source field:</strong>
  <%= @mapping.source_field_id %>
</p>

<p>
  <strong>Target field:</strong>
  <%= @mapping.target_field_id %>
</p>

<p>
  <strong>Bidirectional:</strong>
  <%= @mapping.bidirectional %>
</p>

<p>
  <strong>Synchronization:</strong>
  <%= @mapping.synchronization_id %>
</p>

<%= link_to 'Edit', edit_mapping_path(@mapping) %> |
<%= link_to 'Back', mappings_path %>